name: Code Review

on:
  pull_request:
    branches: master


jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci

      - name: PR Genie 🧞
        uses: david-wagih/PR-Genie@v1.3.1
        with:
          openai-key: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ github.token }} 