name: Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
          
      - name: Install dependencies
        run: npm ci
          
      - name: Generate documentation
        run: npm run docs:generate
        
      - name: Generate dependency graphs
        run: |
          npm run deps:graph
          npm run ngd
          
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation 