name: Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install documentation tools
        run: |
          npm install --save-dev @compodoc/compodoc
          npm install --save-dev madge
          npm install --save-dev @compodoc/ngd-cli @compodoc/ngd-core @compodoc/ngd-transformer
          
      - name: Generate documentation
        run: npm run docs:generate
        
      - name: Generate dependency graphs
        run: |
          npm run deps:graph
          npm run ngd
          
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation 